NHNNEXT/HTML5

- asdfasfdsfas.txt
> test commit

- index.html
> [milooy] First Commit

- asdfasfdsfas.txt
- asset/todolist.js
- index.html
> Homework No.1 첫번 째 숙제입니다.

- asset/handlebars-v3.0.3.js
- asset/todolist.js
- index.html
> 01_1 : add todo with enter key

- asset/base.css
- asset/handlebars-v3.0.3.js
- asset/todolist.js
- index.html
> [Re] todo mission 1,2 

- handlebars-v3.0.3.js
- jquery-1.11.3.js
- test.js
- todo.html
- todo.js
군 전역 직후 기본 내용을 같이 공부하면서 하려니 학습속도가 조금 떨어지는 것 같습니다.
일단 template을 만들어서 li를 추가하는 방식을 구현만 하는데 급급했습니다.
** 
아직 JQuery에 대해서도 미흡하고
template이 작동하는 구조가 정확히 이해가 안됩니다.
자습할 수 있도록 keyword들을 던져주시면 감사하겠습니다.
> 1주차 template 적용 + 2주차 동영상

- asset/todolist.js
> Homework No.2

- asset/base.css
- asset/todolist.js
- handlebars-v3.0.3.js
- index.html
1주차 과제> handlebars.js를 적용해보았습니다.
2주차 과제> 제이쿼리의 on메서드를 이용하여 event delegation을 구현해보았습니다.
기본 css 애니메이션을 구현해보았습니다.
> 1주차, 2주차 과제입니다. - 권다예

- asset/todolist.js
수정해 봤는데 그래도 이상한 부분이 있어요!
ul에 템플릿으로 부터 받은 li을 넣고 넣자마자 애니메이션 효과를 주고 싶은데,
제코드는 뭔가 자연스럽지 않은것 같아요.
> [week2] 코드리뷰에 대한 수정 작업

- asset/base.css
- asset/todolist.js
- index.html
뭔가 석연치 않지만 ㅜㅜ 일단 한 것까지 제출합니다!
제가 생각하는 앞으로의 과제는, 
- 초기 화면에서 데이터를 가져올 때, 순서가 뒤집혀 나온다. 해결 요망.
- 초기 화면에서 데이터를 가져올 때, 완료된 일의 녹색 토글이 꺼진 채로 나온다. (가운데선은 그어져 있는데??) 그래서 완료를 다시 취소하려면 한 번이 아니라 두 번을 클릭해야 한다. 해결 요망.
- 서버와 연동시키는 부분을 jQuery ajax로 바꾸기
- 마구잡이로 코딩한지라.. 정리가 필요.
- 지난 시간에 못한 jQuery 부분 마저 다듬기
입니다만! 
그럼 내일 뵙겠습니다! :)
> 3주차 과제입니다. 

- asset/todolist.js
- index.html
2주차
jQuery 적용 및 이벤트 위임 정리했습니다.
3주차
코드 정리하면서 객체화 시켰습니다~
ajax는 곧 정리하겠습니다.
> week2_complete

- asset/todolist.js
- index.html
1. jquery만 사용
2. dataset, class name, property를 template compile할 때 넣도록 수정
3. event delegate : li마다 이벤트 거는 것을 ul에 한 번에 걸음
4. initData에서 for문을 돌며 append하는 것을 map을 사용하여 수정
> [week03] 리팩토링

- jquery/asset/todolist.js
- nonJquery/asset/todolist.js
1. 온라인 / 오프라인
- 오프라인일 때 localStorage에 저장하기 (완료)
- 온라인일 때 서버에 싱크 맞추기 (미완료)
- localStorage, sessionStorage (완료)
- on/offline (완료)
- (옵션) indexedDB 공부해서 적용하기 (미완료)
> 4주차 과제 1/2 제출합니다

- asset/todolist-jq.js
- asset/todolist.js
- index.html
> week4 구현 완료!

- asset/todolist.js
- index.html
> week3_complete

- todo.css
- todo.html
- todo.js
제가 방향을 제대로 잡은건지는 잘 모르겠습니다만,
localStorage를 이용하여 on/offline 상관없이 dom을 context들을 저장해두었다가 online 때,
local에 저장된 내용을 기반으로 서버 내용을 최신화 시키는 방향으로 구현하고 있습니다.
처음에는 변경사항들만 따로 저장했다가 나중에 그 내용들을 기반으로 수정, clear하려 했는데 제 실력으로는 무리인거같아서 방향을 틀었습니다.
> localStorage 구현. online시 sync 미구현

- asset/todolist.js
- index.html
- jquery-2.1.4.js
[3주차 과제]
- 녹색 토글 문제 해결하였습니다.
- 리스트가 역순으로 나오는 문제 해결하였습니다.
- jQuery Ajax 방식으로 구문을 바꾸었습니다.
[4주차 과제]
- 강의 영상 내용 구현해보았습니다.
- 오프라인 로컬스토리지를 구현해보았습니다. 
- 온라인 서버와의 싱크는 아직 적용하지 못했습니다.
> 3주차 과제 나머지, 4주차 과제(미완)입니다. 

- asset/todolist.js
indexed db 사용하다 실패했어요...ㅠ_ㅠ
onupgradeneeded와 onsuccess 그리고 transaction을 열고 사용하는게 제가 생각한 것 처럼 동작하지 않는 것 같아요.
비동기여서 제가 생각한 순서대로 동작하지 않는 것 같은데 좀 더 공부해봐야겠어요ㅠㅠ!!
> [week05] pushState

- asset/todolist.js
- asset/todosync.js
- index.html
4주차까지 마무리 했습니다.
history 부분은 file로 접근해서 테스트 못 해보고,
주석 걸었다가 다시 풀어서 제출합니다.
> week4_complete

- asset/todolist.js
update 'removeFromOffline' to return Deferred.resolve()
> Milooy - fix issue: $.when

- TODO.md
> first commit

- asset/todolist.js
- index.html
- resource/handlebars-v4.0.5.js
할일에 넣고 엔터를 치면 할일이 추가된다
이벤트를 할당한다.(addEventListener)
할일을 추가한다.(appendChild,insertAdjacentHTML)
추가로 해야 할 일
template 라이브러리를 찾아보고 적용하기
micro template
handlebar
> first step

- TODO.md
- asset/1주차 교수님 예제코드.html
- asset/base.css
- asset/nativeJS.js
- asset/template.js
- asset/todolist.js
- index.html
- lib/handlebars-v4.0.5.js
- lib/jquery-1.12.0.js
강의 2까지는 advanced 수업과 거의 동일하여 금방 완료하였습니다. 나머지 부분도 강의를 통해 진행하며 학습하겠습니다^^
> 2번째 강의까지 완료하였습니다.

- README.md
- asset/base.css
- asset/todolist.js
> 2주차 입니다. #108 

- README.md
- asset/base.css
- asset/todolist.js
> #110 3week auto delegate

- asset/todolist.js
> 4week test

- asset/template.js
- asset/todolist.css
- asset/todolist.js
- index.html
- package.json
> step 3 - fetch 

- asset/todolist.js
> manage filter state & url change history
